# CronJob to save world when players are online
# Only saves if players > 0, touches activity marker for backup gating
apiVersion: batch/v1
kind: CronJob
metadata:
  name: sdtd-auto-save
  namespace: sdtd
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            node-role.kubernetes.io/control-plane: "true"
          tolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
              effect: NoSchedule
          containers:
            - name: save
              image: alpine:3.19
              command: ["/bin/sh", "-c"]
              args:
                - |
                  set -e
                  apk add --no-cache netcat-openbsd >/dev/null 2>&1

                  # Query player count via telnet
                  PLAYERS_OUTPUT=$({
                    sleep 1
                    echo "$TELNET_PASSWORD"
                    sleep 1
                    echo "listplayers"
                    sleep 2
                    echo "exit"
                  } | nc -w 10 sdtd-7dtd-telnet.sdtd.svc.cluster.local 8081 2>&1 || echo "")

                  PLAYER_COUNT=$(echo "$PLAYERS_OUTPUT" | grep -o 'Total of [0-9]*' | grep -o '[0-9]*' || echo "0")
                  echo "[$(date)] Players online: $PLAYER_COUNT"

                  if [ "$PLAYER_COUNT" -gt 0 ]; then
                    echo "[$(date)] Saving world..."

                    # Touch activity marker for backup gating
                    mkdir -p /nfs/sdtd/activity
                    touch /nfs/sdtd/activity/player-activity

                    # Send saveworld command
                    {
                      sleep 1
                      echo "$TELNET_PASSWORD"
                      sleep 1
                      echo "saveworld"
                      sleep 3
                      echo "exit"
                    } | nc -w 10 sdtd-7dtd-telnet.sdtd.svc.cluster.local 8081 2>&1 || true

                    echo "[$(date)] Auto-save completed"
                  else
                    echo "[$(date)] No players - skipping save"
                  fi
              env:
                - name: TELNET_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: sdtd-telnet
                      key: password
              volumeMounts:
                - name: nfs
                  mountPath: /nfs
              resources:
                requests:
                  memory: "32Mi"
                  cpu: "10m"
                limits:
                  memory: "64Mi"
                  cpu: "100m"
          volumes:
            - name: nfs
              nfs:
                server: 10.20.10.20
                path: /volume/567898ba-8471-4adb-9be9-d3e1f96fa7ba/.srv/.unifi-drive/K3sStorage/.data
          restartPolicy: OnFailure
