# 7DTD Save Backup to Synology NFS
# Bypasses broken Helm chart backup - directly copies save data
apiVersion: batch/v1
kind: CronJob
metadata:
  name: sdtd-backup-sync
  namespace: sdtd
spec:
  schedule: "0 */6 * * *"  # Every 6 hours
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            node-role.kubernetes.io/control-plane: "true"
          tolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
              effect: NoSchedule
          containers:
            - name: backup
              image: alpine:latest
              command: ["/bin/sh", "-c"]
              args:
                - |
                  set -e
                  apk add --no-cache rsync curl tar >/dev/null 2>&1

                  # Notify start
                  if [ -n "${TELEGRAM_BOT_TOKEN:-}" ] && [ -n "${TELEGRAM_CHAT_ID:-}" ]; then
                    curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
                      -d chat_id="${TELEGRAM_CHAT_ID}" \
                      -d text="ðŸ”„ 7DTD backup started" >/dev/null || true
                  fi

                  # Find the actual save folder (RWG creates random world names)
                  SAVES_DIR="/gamefiles/UserData/Saves"
                  WORLD_DIR=$(find "$SAVES_DIR" -maxdepth 1 -type d ! -name Saves ! -name Navezgane | head -1)

                  if [ -z "$WORLD_DIR" ]; then
                    echo "ERROR: No world folder found in $SAVES_DIR"
                    ls -la "$SAVES_DIR" || true
                    exit 1
                  fi

                  WORLD_NAME=$(basename "$WORLD_DIR")
                  SAVE_PATH="$WORLD_DIR/FoundationRWG"

                  if [ ! -d "$SAVE_PATH" ]; then
                    echo "ERROR: Save path not found: $SAVE_PATH"
                    ls -la "$WORLD_DIR" || true
                    exit 1
                  fi

                  echo "Found world: $WORLD_NAME"
                  echo "Save path: $SAVE_PATH"

                  DEST_DIR="/dest/7dtd"
                  mkdir -p "$DEST_DIR"

                  # Check if save has changed since last backup (checksum-based)
                  CHECKSUM_FILE="$DEST_DIR/.last-backup-checksum"
                  CURRENT_CHECKSUM=$(find "$SAVE_PATH" -type f -exec md5sum {} \; 2>/dev/null | sort | md5sum | cut -d' ' -f1)
                  LAST_CHECKSUM=$(cat "$CHECKSUM_FILE" 2>/dev/null || echo "none")

                  echo "Current checksum: $CURRENT_CHECKSUM"
                  echo "Last checksum: $LAST_CHECKSUM"

                  if [ "$CURRENT_CHECKSUM" = "$LAST_CHECKSUM" ]; then
                    echo "No changes detected since last backup - skipping"
                    if [ -n "${TELEGRAM_BOT_TOKEN:-}" ] && [ -n "${TELEGRAM_CHAT_ID:-}" ]; then
                      curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
                        -d chat_id="${TELEGRAM_CHAT_ID}" \
                        -d text="â­ï¸ 7DTD backup skipped%0AWorld: ${WORLD_NAME}%0AReason: No changes" >/dev/null || true
                    fi
                    exit 0
                  fi

                  # Create timestamped backup
                  TIMESTAMP=$(date +%Y%m%d-%H%M%S)
                  BACKUP_NAME="7dtd-${WORLD_NAME}-${TIMESTAMP}"

                  # Create tarball of save data
                  echo "Creating backup: ${BACKUP_NAME}.tar.gz"
                  tar -czf "${DEST_DIR}/${BACKUP_NAME}.tar.gz" \
                    -C "$WORLD_DIR" \
                    FoundationRWG

                  # Also sync GeneratedWorlds (world terrain data)
                  GEN_WORLD="/gamefiles/UserData/GeneratedWorlds/$WORLD_NAME"
                  if [ -d "$GEN_WORLD" ]; then
                    echo "Backing up generated world data..."
                    tar -czf "${DEST_DIR}/${BACKUP_NAME}-world.tar.gz" \
                      -C "/gamefiles/UserData/GeneratedWorlds" \
                      "$WORLD_NAME"
                  fi

                  # Save checksum for next run
                  echo "$CURRENT_CHECKSUM" > "$CHECKSUM_FILE"

                  # Keep only last 10 backups (prune oldest save+world pairs)
                  cd "$DEST_DIR"
                  ls -t 7dtd-*[0-9].tar.gz 2>/dev/null | tail -n +11 | while read f; do
                    rm -f "$f" "${f%.tar.gz}-world.tar.gz" 2>/dev/null || true
                  done

                  # Get total backup size
                  BACKUP_SIZE=$(du -sh "$DEST_DIR" | cut -f1)
                  LATEST_SIZE=$(du -sh "${DEST_DIR}/${BACKUP_NAME}.tar.gz" | cut -f1)
                  BACKUP_COUNT=$(ls -1 "$DEST_DIR"/7dtd-*[0-9].tar.gz 2>/dev/null | wc -l | tr -d ' ')

                  echo "Backup complete!"
                  echo "Latest: ${BACKUP_NAME}.tar.gz ($LATEST_SIZE)"
                  echo "Total backups: $BACKUP_COUNT ($BACKUP_SIZE)"
                  ls -lht "$DEST_DIR" | head -12

                  # Notify completion
                  if [ -n "${TELEGRAM_BOT_TOKEN:-}" ] && [ -n "${TELEGRAM_CHAT_ID:-}" ]; then
                    curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
                      -d chat_id="${TELEGRAM_CHAT_ID}" \
                      -d text="âœ… 7DTD backup complete%0AWorld: ${WORLD_NAME}%0ASize: ${LATEST_SIZE}%0ABackups: ${BACKUP_COUNT}/10 (${BACKUP_SIZE})" >/dev/null || true
                  fi
              env:
                - name: TELEGRAM_BOT_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: telegram-credentials
                      key: bot-token
                      optional: true
                - name: TELEGRAM_CHAT_ID
                  valueFrom:
                    secretKeyRef:
                      name: telegram-credentials
                      key: chat-id
                      optional: true
              volumeMounts:
                - name: gamefiles
                  mountPath: /gamefiles
                  readOnly: true
                - name: dest
                  mountPath: /dest
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "100m"
                limits:
                  memory: "512Mi"
                  cpu: "500m"
          volumes:
            - name: gamefiles
              persistentVolumeClaim:
                claimName: sdtd-7dtd-gamefiles
            - name: dest
              nfs:
                server: 10.20.11.10
                path: /volume1/k3s-backups
          restartPolicy: OnFailure
