# PostgreSQL backup CronJob - daily pg_dump to UNAS K3sStorage
# Runs at 3 AM daily, keeps last 7 days of backups
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgresql-backup
  namespace: databases
spec:
  schedule: "0 3 * * *"  # 3 AM daily
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            node-role.kubernetes.io/control-plane: "true"
          tolerations:
            - key: "node-role.kubernetes.io/control-plane"
              operator: "Exists"
              effect: "NoSchedule"
          containers:
          - name: backup
            image: postgres:18-alpine
            command:
            - /bin/sh
            - -c
            - |
              set -e
              apk add --no-cache curl >/dev/null 2>&1

              DEST_DIR="/backup/postgresql/backups"
              HISTORY_DIR="$DEST_DIR/history"
              mkdir -p "$DEST_DIR" "$HISTORY_DIR"

              TIMESTAMP=$(date +%Y%m%d_%H%M%S)
              BACKUP_FILE="${HISTORY_DIR}/postgresql_${TIMESTAMP}.sql.gz"

              echo "Starting PostgreSQL backup at $(date)"
              echo "Backup file: ${BACKUP_FILE}"

              # Notify start
              if [ -n "${TELEGRAM_BOT_TOKEN:-}" ] && [ -n "${TELEGRAM_CHAT_ID:-}" ]; then
                curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
                  -d chat_id="${TELEGRAM_CHAT_ID}" \
                  -d text="🔄 PostgreSQL backup started" >/dev/null || true
              fi

              # Dump all databases, compress output
              PGPASSWORD="${POSTGRES_PASSWORD}" pg_dumpall \
                -h postgresql.databases.svc.cluster.local \
                -U postgres \
                | gzip > "${BACKUP_FILE}"

              # Create latest.sql.gz for easy Mac access
              cp "${BACKUP_FILE}" "${DEST_DIR}/latest.sql.gz"

              # Verify backup was created
              ls -lh "${BACKUP_FILE}"

              # Keep only last 7 timestamped backups in history
              echo "Cleaning up old backups..."
              cd "$HISTORY_DIR"
              ls -t postgresql_*.sql.gz 2>/dev/null | tail -n +8 | while read f; do
                rm -f "$f" 2>/dev/null || true
              done

              # Get stats
              BACKUP_SIZE=$(du -sh "${DEST_DIR}/latest.sql.gz" | cut -f1)
              BACKUP_COUNT=$(ls -1 "$HISTORY_DIR"/postgresql_*.sql.gz 2>/dev/null | wc -l | tr -d ' ')

              echo "Backup complete at $(date)"
              echo "Latest: latest.sql.gz ($BACKUP_SIZE)"
              echo "Total backups: $BACKUP_COUNT"
              ls -lh "$DEST_DIR/"

              # Notify completion
              if [ -n "${TELEGRAM_BOT_TOKEN:-}" ] && [ -n "${TELEGRAM_CHAT_ID:-}" ]; then
                curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
                  -d chat_id="${TELEGRAM_CHAT_ID}" \
                  -d text="✅ PostgreSQL backup complete%0ASize: ${BACKUP_SIZE}%0ABackups: ${BACKUP_COUNT}/7" >/dev/null || true
              fi
            env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: postgres-password
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: telegram-credentials
                  key: bot-token
                  optional: true
            - name: TELEGRAM_CHAT_ID
              valueFrom:
                secretKeyRef:
                  name: telegram-credentials
                  key: chat-id
                  optional: true
            volumeMounts:
            - name: backup
              mountPath: /backup
            resources:
              requests:
                memory: "128Mi"
                cpu: "100m"
              limits:
                memory: "512Mi"
                cpu: "500m"
          volumes:
          - name: backup
            nfs:
              server: 10.20.10.20
              path: /volume/567898ba-8471-4adb-9be9-d3e1f96fa7ba/.srv/.unifi-drive/K3sStorage/.data
          restartPolicy: OnFailure
