# PostgreSQL backup CronJob - daily pg_dump to Synology NFS
# Runs at 3 AM daily, keeps last 7 days of backups
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgresql-backup
  namespace: databases
spec:
  schedule: "0 3 * * *"  # 3 AM daily
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          hostNetwork: true  # Required to access Synology NFS
          dnsPolicy: ClusterFirstWithHostNet  # Allow cluster DNS with hostNetwork
          nodeSelector:
            node-role.kubernetes.io/control-plane: "true"
          tolerations:
            - key: "node-role.kubernetes.io/control-plane"
              operator: "Exists"
              effect: "NoSchedule"
          containers:
          - name: backup
            image: postgres:18-alpine
            command:
            - /bin/sh
            - -c
            - |
              set -e
              TIMESTAMP=$(date +%Y%m%d_%H%M%S)
              BACKUP_FILE="/backup/postgresql_${TIMESTAMP}.sql.gz"

              echo "Starting PostgreSQL backup at $(date)"
              echo "Backup file: ${BACKUP_FILE}"

              # Dump all databases, compress output
              PGPASSWORD="${POSTGRES_PASSWORD}" pg_dumpall \
                -h postgresql.databases.svc.cluster.local \
                -U postgres \
                | gzip > "${BACKUP_FILE}"

              # Verify backup was created
              ls -lh "${BACKUP_FILE}"

              # Keep only last 7 days of backups
              echo "Cleaning up old backups..."
              find /backup -name "postgresql_*.sql.gz" -mtime +7 -delete

              echo "Backup complete at $(date)"
              ls -lh /backup/
            env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: postgres-password
            volumeMounts:
            - name: backup
              mountPath: /backup
            securityContext:
              privileged: true  # Required for NFS mount
          volumes:
          - name: backup
            nfs:
              server: 10.20.11.10
              path: /volume1/k3s-backups
          restartPolicy: OnFailure
