# Open-WebUI SQLite Backup CronJob - daily to UNAS K3sStorage
# Backs up webui.db (conversation history) for Mac accessibility
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: open-webui-backup
  namespace: open-webui
spec:
  schedule: "0 4 * * *"  # 4 AM daily (after PostgreSQL at 3 AM)
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            node-role.kubernetes.io/control-plane: "true"
          tolerations:
            - key: "node-role.kubernetes.io/control-plane"
              operator: "Exists"
              effect: "NoSchedule"
          containers:
          - name: backup
            image: alpine:latest
            command: ["/bin/sh", "-c"]
            args:
              - |
                set -e
                apk add --no-cache curl sqlite >/dev/null 2>&1

                DEST_DIR="/dest/open-webui/backups"
                HISTORY_DIR="$DEST_DIR/history"
                mkdir -p "$DEST_DIR" "$HISTORY_DIR"

                SOURCE_DB="/data/webui.db"

                if [ ! -f "$SOURCE_DB" ]; then
                  echo "ERROR: webui.db not found at $SOURCE_DB"
                  ls -la /data/ || true
                  exit 1
                fi

                echo "Starting Open-WebUI backup at $(date)"

                # Notify start
                if [ -n "${TELEGRAM_BOT_TOKEN:-}" ] && [ -n "${TELEGRAM_CHAT_ID:-}" ]; then
                  curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
                    -d chat_id="${TELEGRAM_CHAT_ID}" \
                    -d text="ðŸ”„ Open-WebUI backup started" >/dev/null || true
                fi

                # Check if DB has changed since last backup (checksum-based)
                CHECKSUM_FILE="$DEST_DIR/.last-backup-checksum"
                CURRENT_CHECKSUM=$(md5sum "$SOURCE_DB" | cut -d' ' -f1)
                LAST_CHECKSUM=$(cat "$CHECKSUM_FILE" 2>/dev/null || echo "none")

                echo "Current checksum: $CURRENT_CHECKSUM"
                echo "Last checksum: $LAST_CHECKSUM"

                if [ "$CURRENT_CHECKSUM" = "$LAST_CHECKSUM" ]; then
                  echo "No changes detected since last backup - skipping"
                  if [ -n "${TELEGRAM_BOT_TOKEN:-}" ] && [ -n "${TELEGRAM_CHAT_ID:-}" ]; then
                    curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
                      -d chat_id="${TELEGRAM_CHAT_ID}" \
                      -d text="â­ï¸ Open-WebUI backup skipped%0AReason: No changes" >/dev/null || true
                  fi
                  exit 0
                fi

                # Create timestamped backup using sqlite backup command (safe for running DB)
                TIMESTAMP=$(date +%Y%m%d_%H%M%S)
                BACKUP_FILE="${HISTORY_DIR}/webui_${TIMESTAMP}.db"

                echo "Creating backup: ${BACKUP_FILE}"
                sqlite3 "$SOURCE_DB" ".backup '${BACKUP_FILE}'"

                # Save checksum for next run
                echo "$CURRENT_CHECKSUM" > "$CHECKSUM_FILE"

                # Create latest.db for easy Mac access
                cp "${BACKUP_FILE}" "${DEST_DIR}/latest.db"

                # Keep only last 7 timestamped backups in history
                cd "$HISTORY_DIR"
                ls -t webui_*.db 2>/dev/null | tail -n +8 | while read f; do
                  rm -f "$f" 2>/dev/null || true
                done

                # Get stats
                BACKUP_SIZE=$(du -sh "${DEST_DIR}/latest.db" | cut -f1)
                BACKUP_COUNT=$(ls -1 "$HISTORY_DIR"/webui_*.db 2>/dev/null | wc -l | tr -d ' ')

                echo "Backup complete at $(date)"
                echo "Latest: latest.db ($BACKUP_SIZE)"
                echo "Total backups: $BACKUP_COUNT"
                ls -lh "$DEST_DIR/"

                # Notify completion
                if [ -n "${TELEGRAM_BOT_TOKEN:-}" ] && [ -n "${TELEGRAM_CHAT_ID:-}" ]; then
                  curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
                    -d chat_id="${TELEGRAM_CHAT_ID}" \
                    -d text="âœ… Open-WebUI backup complete%0ASize: ${BACKUP_SIZE}%0ABackups: ${BACKUP_COUNT}/7" >/dev/null || true
                fi
            env:
              - name: TELEGRAM_BOT_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: telegram-credentials
                    key: bot-token
                    optional: true
              - name: TELEGRAM_CHAT_ID
                valueFrom:
                  secretKeyRef:
                    name: telegram-credentials
                    key: chat-id
                    optional: true
            volumeMounts:
              - name: data
                mountPath: /data
                readOnly: true
              - name: dest
                mountPath: /dest
            resources:
              requests:
                memory: "64Mi"
                cpu: "50m"
              limits:
                memory: "256Mi"
                cpu: "200m"
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: open-webui-data
            - name: dest
              nfs:
                server: 10.20.10.20
                path: /volume/567898ba-8471-4adb-9be9-d3e1f96fa7ba/.srv/.unifi-drive/K3sStorage/.data
          restartPolicy: OnFailure
