# Factorio Save Backup to UNAS K3sStorage
# Backs up saves to NAS for Mac accessibility and disaster recovery
apiVersion: batch/v1
kind: CronJob
metadata:
  name: factorio-backup
  namespace: factorio
spec:
  schedule: "0 */6 * * *"  # Every 6 hours
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            node-role.kubernetes.io/control-plane: "true"
          tolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
              effect: NoSchedule
          containers:
            - name: backup
              image: alpine:latest
              command: ["/bin/sh", "-c"]
              args:
                - |
                  set -e
                  apk add --no-cache curl >/dev/null 2>&1

                  # Notify start
                  if [ -n "${TELEGRAM_BOT_TOKEN:-}" ] && [ -n "${TELEGRAM_CHAT_ID:-}" ]; then
                    curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
                      -d chat_id="${TELEGRAM_CHAT_ID}" \
                      -d text="ðŸ”„ Factorio backup started" >/dev/null || true
                  fi

                  # Find latest save file
                  SAVES_DIR="/factorio/saves"
                  LATEST_SAVE=$(ls -t "$SAVES_DIR"/*.zip 2>/dev/null | head -1)

                  if [ -z "$LATEST_SAVE" ]; then
                    echo "ERROR: No save files found in $SAVES_DIR"
                    ls -la "$SAVES_DIR" || true
                    exit 1
                  fi

                  SAVE_NAME=$(basename "$LATEST_SAVE")
                  echo "Latest save: $SAVE_NAME"

                  DEST_DIR="/dest/factorio/backups"
                  HISTORY_DIR="$DEST_DIR/history"
                  mkdir -p "$DEST_DIR" "$HISTORY_DIR"

                  # Check if save has changed since last backup (checksum-based)
                  CHECKSUM_FILE="$DEST_DIR/.last-backup-checksum"
                  CURRENT_CHECKSUM=$(md5sum "$LATEST_SAVE" | cut -d' ' -f1)
                  LAST_CHECKSUM=$(cat "$CHECKSUM_FILE" 2>/dev/null || echo "none")

                  echo "Current checksum: $CURRENT_CHECKSUM"
                  echo "Last checksum: $LAST_CHECKSUM"

                  if [ "$CURRENT_CHECKSUM" = "$LAST_CHECKSUM" ]; then
                    echo "No changes detected since last backup - skipping"
                    if [ -n "${TELEGRAM_BOT_TOKEN:-}" ] && [ -n "${TELEGRAM_CHAT_ID:-}" ]; then
                      curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
                        -d chat_id="${TELEGRAM_CHAT_ID}" \
                        -d text="â­ï¸ Factorio backup skipped%0ASave: ${SAVE_NAME}%0AReason: No changes" >/dev/null || true
                    fi
                    exit 0
                  fi

                  # Create timestamped backup in history
                  TIMESTAMP=$(date +%Y%m%d-%H%M%S)
                  BACKUP_NAME="factorio-${TIMESTAMP}.zip"

                  echo "Creating backup: ${BACKUP_NAME}"
                  cp "$LATEST_SAVE" "${HISTORY_DIR}/${BACKUP_NAME}"

                  # Save checksum for next run
                  echo "$CURRENT_CHECKSUM" > "$CHECKSUM_FILE"

                  # Create latest.zip for easy Mac access (overwrites previous)
                  cp "${HISTORY_DIR}/${BACKUP_NAME}" "${DEST_DIR}/latest.zip"

                  # Keep only last 5 timestamped backups in history
                  cd "$HISTORY_DIR"
                  ls -t factorio-*.zip 2>/dev/null | tail -n +6 | while read f; do
                    rm -f "$f" 2>/dev/null || true
                  done

                  # Get stats
                  BACKUP_SIZE=$(du -sh "$DEST_DIR" | cut -f1)
                  LATEST_SIZE=$(du -sh "${DEST_DIR}/latest.zip" | cut -f1)
                  BACKUP_COUNT=$(ls -1 "$HISTORY_DIR"/factorio-*.zip 2>/dev/null | wc -l | tr -d ' ')

                  echo "Backup complete!"
                  echo "Latest: latest.zip ($LATEST_SIZE)"
                  echo "Total backups: $BACKUP_COUNT timestamped + latest ($BACKUP_SIZE)"
                  ls -lht "$DEST_DIR" | head -10

                  # Notify completion
                  if [ -n "${TELEGRAM_BOT_TOKEN:-}" ] && [ -n "${TELEGRAM_CHAT_ID:-}" ]; then
                    curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
                      -d chat_id="${TELEGRAM_CHAT_ID}" \
                      -d text="âœ… Factorio backup complete%0ASave: ${SAVE_NAME}%0ASize: ${LATEST_SIZE}%0ABackups: ${BACKUP_COUNT}/5 + latest (${BACKUP_SIZE})" >/dev/null || true
                  fi
              env:
                - name: TELEGRAM_BOT_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: telegram-credentials
                      key: bot-token
                      optional: true
                - name: TELEGRAM_CHAT_ID
                  valueFrom:
                    secretKeyRef:
                      name: telegram-credentials
                      key: chat-id
                      optional: true
              volumeMounts:
                - name: factorio-data
                  mountPath: /factorio
                  readOnly: true
                - name: dest
                  mountPath: /dest
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "50m"
                limits:
                  memory: "256Mi"
                  cpu: "200m"
          volumes:
            - name: factorio-data
              persistentVolumeClaim:
                claimName: factorio-factorio-server-charts-datadir
            - name: dest
              nfs:
                server: 10.20.10.20
                path: /volume/567898ba-8471-4adb-9be9-d3e1f96fa7ba/.srv/.unifi-drive/K3sStorage/.data
          restartPolicy: OnFailure
