# PVC for mapshot rendered output and checksum tracking
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mapshot-data
  namespace: mapshot
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
