# Mapshot GPU All Surfaces Test - Hardware OpenGL rendering on RTX 4000 Ada
# Surface: ALL (nauvis + planets/platforms) | Resolution: 2048px | Expected: 10-40 minutes
---
apiVersion: batch/v1
kind: Job
metadata:
  name: mapshot-render-gpu-all
  namespace: mapshot
  labels:
    test-scenario: "gpu-hardware-all-surfaces"
    resolution: "2048"
    surface: "all"
spec:
  backoffLimit: 0  # Don't retry on failure - we want clean test data
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        test-scenario: "gpu-hardware-all-surfaces"
    spec:
      serviceAccountName: mapshot-render
      restartPolicy: Never
      
      # GPU node scheduling (same pattern as Ollama)
      runtimeClassName: nvidia
      nodeSelector:
        nvidia.com/gpu.present: "true"
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "gpu"
          effect: "NoSchedule"
      
      containers:
        - name: render
          image: martydingo/mapshot:latest
          command: ["/bin/bash", "-c"]
          args:
            - |
              set -euo pipefail
              
              # =============================================================================
              # TEST CONFIGURATION
              # =============================================================================
              TEST_NAME="GPU Hardware OpenGL - All Surfaces (RTX 4000 Ada)"
              TEST_START=$(date +%s)
              
              # =============================================================================
              # PATH CONSTANTS
              # =============================================================================
              PVC_ROOT="/mapshot"
              FACTORIO_DIR="$PVC_ROOT/factorio"
              FACTORIO_BIN="$FACTORIO_DIR/bin/x64/factorio"
              SCRIPT_OUTPUT="$FACTORIO_DIR/script-output"
              VIEWER_DIR="$SCRIPT_OUTPUT/mapshot/latest"
              NAS_DEST="/nas/${MAPSHOT_OUTPUT_SUFFIX}"
              
              # Save file location (pre-copied to PVC for testing)
              SAVE_FILE="$PVC_ROOT/test-save.zip"
              
              # =============================================================================
              # HELPER FUNCTIONS
              # =============================================================================
              log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"; }
              error() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] ERROR: $*" >&2; }
              
              log_test_result() {
                local status=$1
                local message=$2
                local duration=$(($(date +%s) - TEST_START))
                log "=========================================="
                log "TEST: $TEST_NAME"
                log "STATUS: $status"
                log "DURATION: ${duration}s ($(($duration / 60))m $(($duration % 60))s)"
                log "MESSAGE: $message"
                log "=========================================="
              }
              
              # =============================================================================
              # STEP 1: PRE-FLIGHT CHECKS
              # =============================================================================
              log "=== STEP 1: Pre-flight Checks ==="
              
              # Check GPU availability
              if ! nvidia-smi &>/dev/null; then
                error "nvidia-smi not available"
                log_test_result "FAIL" "GPU not accessible"
                exit 1
              fi
              log "✓ GPU detected:"
              nvidia-smi --query-gpu=name,memory.total,driver_version --format=csv,noheader
              
              # Check Factorio installation
              if [ ! -f "$FACTORIO_BIN" ]; then
                error "Factorio not found at $FACTORIO_BIN"
                error "Please pre-install Factorio on PVC before running tests"
                log_test_result "FAIL" "Factorio not installed"
                exit 1
              fi
              FACTORIO_VERSION=$("$FACTORIO_BIN" --version 2>/dev/null | head -1 || echo "unknown")
              log "✓ Factorio binary: $FACTORIO_VERSION"
              
              # Check save file exists (should be pre-copied for testing)
              if [ ! -f "$SAVE_FILE" ]; then
                error "Test save not found at $SAVE_FILE"
                error "Copy a save to PVC: kubectl cp <save.zip> mapshot/<pod>:/mapshot/test-save.zip"
                log_test_result "FAIL" "Save file missing"
                exit 1
              fi
              SAVE_SIZE=$(du -h "$SAVE_FILE" | cut -f1)
              log "✓ Save file: $SAVE_SIZE"
              
              # Check NAS mount
              if [ ! -d "/nas" ]; then
                error "NAS not mounted at /nas"
                log_test_result "FAIL" "NAS mount missing"
                exit 1
              fi
              log "✓ NAS mounted"
              
              log "Pre-flight checks passed"
              
              # =============================================================================
              # STEP 2: CLEAR STALE STATE
              # =============================================================================
              log "=== STEP 2: Clear Stale State ==="
              
              # Remove stale lock file
              if [ -f "$FACTORIO_DIR/.lock" ]; then
                log "Removing stale lock file"
                rm -f "$FACTORIO_DIR/.lock"
              fi
              
              # Clear previous render output
              if [ -d "$VIEWER_DIR" ]; then
                log "Clearing previous render: $VIEWER_DIR"
                rm -rf "$VIEWER_DIR"
              fi
              mkdir -p "$VIEWER_DIR"
              
              # Clear NAS output directory
              if [ -d "$NAS_DEST" ]; then
                log "Clearing previous NAS output: $NAS_DEST"
                rm -rf "$NAS_DEST"
              fi
              mkdir -p "$NAS_DEST"
              
              log "State cleared"
              
              # =============================================================================
              # STEP 3: RUN MAPSHOT RENDER
              # =============================================================================
              log "=== STEP 3: Run Mapshot Render ==="
              log "Configuration:"
              log "  Resolution: ${MAPSHOT_RESOLUTION}px"
              log "  Surface: ${MAPSHOT_SURFACE}"
              log "  Area: ${MAPSHOT_AREA}"
              log "  Timeout: ${MAPSHOT_INTERVAL}s"
              log "  Output: $NAS_DEST"
              
              RENDER_START=$(date +%s)
              log "Starting render at $(date)"
              
              # Run with verbose logging and timeout
              if timeout ${MAPSHOT_INTERVAL} xvfb-run -a mapshot render \
                --logtostderr \
                --factorio_binary "$FACTORIO_BIN" \
                --factorio_datadir "$FACTORIO_DIR" \
                --work_dir "$FACTORIO_DIR" \
                --area "${MAPSHOT_AREA}" \
                --resolution "${MAPSHOT_RESOLUTION}" \
                --jpgquality "${MAPSHOT_JPEG_QUALITY}" \
                --surface "${MAPSHOT_SURFACE}" \
                --factorio_verbose \
                -v 9 \
                "$SAVE_FILE"; then
                
                RENDER_DURATION=$(($(date +%s) - RENDER_START))
                log "✓ Render completed in ${RENDER_DURATION}s ($(($RENDER_DURATION / 60))m)"
              else
                RENDER_EXIT=$?
                RENDER_DURATION=$(($(date +%s) - RENDER_START))
                error "Render failed with exit code $RENDER_EXIT after ${RENDER_DURATION}s"
                
                if [ $RENDER_EXIT -eq 124 ]; then
                  log_test_result "TIMEOUT" "Render exceeded ${MAPSHOT_INTERVAL}s timeout"
                else
                  log_test_result "FAIL" "Render crashed (exit $RENDER_EXIT)"
                fi
                exit $RENDER_EXIT
              fi
              
              # =============================================================================
              # STEP 4: VALIDATE OUTPUT
              # =============================================================================
              log "=== STEP 4: Validate Output ==="
              
              # Check for render directories
              RENDER_DIR=$(ls -td "$VIEWER_DIR"/d-* 2>/dev/null | head -1)
              if [ -z "$RENDER_DIR" ]; then
                error "No render directory found in $VIEWER_DIR"
                log "Contents:"
                ls -la "$VIEWER_DIR" 2>/dev/null || echo "(empty)"
                log_test_result "FAIL" "No render output generated"
                exit 1
              fi
              
              RENDER_NAME=$(basename "$RENDER_DIR")
              log "✓ Render directory: $RENDER_NAME"
              
              # Check for mapshot.json
              if [ ! -f "$RENDER_DIR/mapshot.json" ]; then
                error "mapshot.json missing from $RENDER_DIR"
                log_test_result "FAIL" "Incomplete render (missing metadata)"
                exit 1
              fi
              log "✓ Metadata file present"
              
              # Count tiles generated
              TILE_COUNT=$(find "$RENDER_DIR" -name "tile_*.jpg" 2>/dev/null | wc -l)
              log "✓ Tiles generated: $TILE_COUNT"
              
              # Check output size
              OUTPUT_SIZE=$(du -sh "$RENDER_DIR" | cut -f1)
              log "✓ Output size: $OUTPUT_SIZE"
              
              log "Output validation passed"
              
              # =============================================================================
              # STEP 5: COPY TO NAS
              # =============================================================================
              log "=== STEP 5: Copy to NAS ==="
              
              log "Copying render output to $NAS_DEST..."
              cp -r "$VIEWER_DIR"/* "$NAS_DEST/" 2>/dev/null || {
                error "Failed to copy to NAS"
                log_test_result "FAIL" "NAS copy failed"
                exit 1
              }
              
              NAS_SIZE=$(du -sh "$NAS_DEST" | cut -f1)
              log "✓ NAS copy complete: $NAS_SIZE"
              
              # =============================================================================
              # STEP 6: FINAL SUMMARY
              # =============================================================================
              log "=== STEP 6: Final Summary ==="
              
              TOTAL_DURATION=$(($(date +%s) - TEST_START))
              
              log_test_result "SUCCESS" "Render completed successfully"
              log "Tiles: $TILE_COUNT"
              log "Output: $OUTPUT_SIZE"
              log "NAS location: $NAS_DEST"
              log "Render time: ${RENDER_DURATION}s"
              log "Total time: ${TOTAL_DURATION}s"
              
              # Write test results to file for easy parsing
              cat > "$NAS_DEST/test-results.txt" <<EOF
              TEST_NAME=$TEST_NAME
              STATUS=SUCCESS
              RENDER_DURATION=${RENDER_DURATION}
              TOTAL_DURATION=${TOTAL_DURATION}
              TILE_COUNT=$TILE_COUNT
              OUTPUT_SIZE=$OUTPUT_SIZE
              RESOLUTION=${MAPSHOT_RESOLUTION}
              SURFACE=${MAPSHOT_SURFACE}
              FACTORIO_VERSION=$FACTORIO_VERSION
              GPU_MODEL=$(nvidia-smi --query-gpu=name --format=csv,noheader)
              TIMESTAMP=$(date -Iseconds)
              EOF
              
              log "Test results saved to $NAS_DEST/test-results.txt"
              log "Test complete!"
          
          env:
            - name: MAPSHOT_INTERVAL
              value: "3600"  # 1 hour timeout (more surfaces)
            - name: MAPSHOT_RESOLUTION
              value: "2048"
            - name: MAPSHOT_AREA
              value: "all"  # all chunks
            - name: MAPSHOT_SURFACE
              value: "_all_"  # ALL surfaces (nauvis + planets)
            - name: MAPSHOT_JPEG_QUALITY
              value: "90"
            - name: MAPSHOT_OUTPUT_SUFFIX
              value: "gpu-all-2048"
            - name: FACTORIO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: factorio-credentials
                  key: username
            - name: FACTORIO_TOKEN
              valueFrom:
                secretKeyRef:
                  name: factorio-credentials
                  key: token
          
          resources:
            requests:
              memory: "4Gi"
              cpu: "2"
              nvidia.com/gpu: "1"
            limits:
              memory: "16Gi"
              cpu: "4"
              nvidia.com/gpu: "1"
          
          volumeMounts:
            - name: mapshot-data
              mountPath: /mapshot
            - name: nas-dest
              mountPath: /nas
              subPath: mapshot
      
      volumes:
        - name: mapshot-data
          persistentVolumeClaim:
            claimName: mapshot-data
        - name: nas-dest
          hostPath:
            path: /mnt/k3s-nfs
            type: Directory
